### ISSUE TITLE
Panic when advertising data

### ISSUE THREAD

**Issue by MrMinimal** [mwylde/rumble#26]
First: Thank you for this library, this is what got me into Rust programming!

# Problem
When I start my [light bulb control ](https://gitlab.com/MrMinimal/minger-led-bulb-control) I get no panics.
Usually that is. But if I let it run for a couple of hours, at one point it panics with the following log (which prints a lot of words twice for some reason):

<details><summary>Spoiler</summary>
<p>

```rust
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'attempt to subtract with overflowattempt to subtract with overflow', ', /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec8
23/rumble-0.2.1/src/bluez/protocol/hci.rs/home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/rumble-0.2.1/src/bluez/protocol/hci.rs::442442::1515

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::panicking::panic
             at libcore/panicking.rs:52
   9: rumble::bluez::protocol::hci::le_advertising_data
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/rumble-0.2.1/src/bluez/protocol/hci.rs:442
  10: rumble::bluez::protocol::hci::le_advertising_info
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/rumble-0.2.1/<::nom::macros::named macros>:13
  11: rumble::bluez::protocol::hci::le_meta_event
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/rumble-0.2.1/src/bluez/protocol/hci.rs:586
  12: rumble::bluez::protocol::hci::hci_event_pkt
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/rumble-0.2.1/src/bluez/protocol/hci.rs:659
  13: rumble::bluez::protocol::hci::message
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/rumble-0.2.1/src/bluez/protocol/hci.rs:740
  14: rumble::bluez::adapter::ConnectedAdapter::add_raw_socket_reader::{{closure}}
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/rumble-0.2.1/src/bluez/adapter/mod.rs:256
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

---
The bug seems to happen in this line: https://github.com/mwylde/rumble/blob/889bdcad8ceb91b59c975ced92f19fe97ed9a837/src/bluez/protocol/hci.rs#L441

I'd really appreciate any help on narrowing this bug down. This is my first Rust project so I don't know too many debugging tips.

Cheers!

**Comment by mwylde** [comment]
Thanks for the report -- this is definitely a bug in the protocol implementation. If the length is 0 for some reason (either the peripheral sends the wrong value or we get lost in the stream) we'll get -1, which (in debug mode) causes a panic due to overflow.

This code should have a check, and cause a failure if length is non-positive. I'm happy to help with that PR if you're interested. Note that you also will not see this if you compile in production mode (in theory it could cause bad behavior, but in practice the length read will fail and we'll return an error).

**Comment by lautis** [comment]
I've also run into this occasionally. In debug mode happens exactly as described, in release mode the error is a bit more cryptic:

```
thread '<unnamed>' panicked at 'slice index starts at 4294967295 but ends at 1', src/libcore/slice/mod.rs:2355:5
```

<details>
  <summary>Backtrace</summary>
```
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
              at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
    1: std::panicking::default_hook::{{closure}}
              at src/libstd/sys_common/backtrace.rs:71
              at src/libstd/sys_common/backtrace.rs:59
              at src/libstd/panicking.rs:211
    2: std::panicking::rust_panic_with_hook
              at src/libstd/panicking.rs:227
              at src/libstd/panicking.rs:491
    3: std::panicking::continue_panic_fmt
              at src/libstd/panicking.rs:398
    4: rust_begin_unwind
              at src/libstd/panicking.rs:325
    5: core::panicking::panic_fmt
              at src/libcore/panicking.rs:95
    6: core::slice::slice_index_order_fail
              at src/libcore/slice/mod.rs:2355
```
</details>
